// @ts-check
import { defineConfig } from 'astro/config';

import starlight from '@astrojs/starlight';

import cloudflare from '@astrojs/cloudflare';

const FONTS_LINK =
  'https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400&family=JetBrains+Mono:wght@400;500;700&display=swap';

// https://astro.build/config
export default defineConfig({
  server: {
    port: 4321,
  },

  integrations: [
    starlight({
      title: 'Grove',
      description: 'Feature documentation for Grove, a native Android org-mode note-taking app.',
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/rrajath/grove' }],
      customCss: ['./src/styles/tokens.css', './src/styles/starlight-overrides.css'],
      head: [
        { tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' } },
        { tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true } },
        { tag: 'link', attrs: { rel: 'stylesheet', href: FONTS_LINK } },
      ],
      components: {
        PageTitle: './src/components/starlight-overrides/PageTitle.astro',
        ThemeProvider: './src/components/starlight-overrides/ThemeProvider.astro',
        ThemeSelect: './src/components/starlight-overrides/ThemeSelect.astro',
      },
      // Hand-written (not autogenerated) so the grouping matches the ordering in
      // src/content/docs/features/index.mdx. The Widget page intentionally has no sidebar entry, per the design
      // handoff's instruction to exclude it from navigation until it ships — the page
      // still exists and is reachable directly at /features/widget.
      sidebar: [
        { label: 'Overview', link: '/features/' },
        {
          label: 'Getting started',
          collapsed: true,
          items: [
            { label: 'Onboarding', link: '/features/onboarding' },
            { label: 'Notebooks', link: '/features/notebooks' },
            {
              label: 'Sync',
              link: '/features/sync',
              badge: { text: 'also in Sync and conflicts', variant: 'note' },
            },
          ],
        },
        {
          label: 'Notes: reading and editing',
          collapsed: true,
          items: [
            { label: 'Outline View', link: '/features/outline-view' },
            { label: 'Read Mode', link: '/features/read-mode' },
            { label: 'Edit Mode', link: '/features/edit-mode' },
            { label: 'Metadata Sheet', link: '/features/metadata-sheet' },
            { label: 'Planning Dates', link: '/features/planning-dates' },
            { label: 'Refile', link: '/features/refile' },
            { label: 'Undo', link: '/features/undo' },
          ],
        },
        {
          label: 'Capture',
          collapsed: true,
          items: [
            { label: 'Capture', link: '/features/capture' },
            { label: 'Capture Templates', link: '/features/capture-templates' },
            { label: 'Placeholders', link: '/features/placeholders' },
            { label: 'Share Intake', link: '/features/share-intake' },
          ],
        },
        {
          label: 'Finding things',
          collapsed: true,
          items: [
            { label: 'Agenda', link: '/features/agenda' },
            { label: 'Search', link: '/features/search' },
          ],
        },
        {
          label: 'Sync and conflicts',
          collapsed: true,
          items: [
            { label: 'Sync', link: '/features/sync' },
            { label: 'Conflict Resolution', link: '/features/conflict-resolution' },
          ],
        },
        {
          label: 'Reminders',
          collapsed: true,
          items: [{ label: 'Reminders', link: '/features/reminders' }],
        },
        {
          label: 'Settings',
          collapsed: true,
          items: [
            { label: 'Settings Overview', link: '/features/settings-overview' },
            { label: 'Themes & Appearance', link: '/features/themes-appearance' },
            { label: 'Notes Behavior', link: '/features/notes-behavior' },
            { label: 'Backup (Export / Import)', link: '/features/backup-export-import' },
          ],
        },
        { label: 'Privacy Policy', link: '/privacy-policy' },
      ],
    }),
  ],

  // Default is runtime image transforms via Cloudflare Images (a paid,
  // separately-provisioned product) — every <Image> renders as /_image?...
  // and 404s unless that's set up. This is a static site with a fixed set of
  // known screenshots, so optimize them at build time instead; no runtime
  // dependency needed.
  adapter: cloudflare({ imageService: 'compile' }),
});